name: Release

on:
  pull_request:
    branches:
      - release

jobs:
  Main-Pipeline:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dependencies
        run:  |
              sudo apt-get install -y \
                flatpak \
                libgtest-dev \
                cmake-format \
                clang-tidy \
                cppcheck \
                lcov

      - name: Format Check
        run:  ${{github.workspace}}/format-check.sh

      - name: CppCheck
        run:  ${{github.workspace}}/cppcheck.sh

      - name: Build Release
        run:  ${{github.workspace}}/build.sh rel

      - name: Clang Tidy
        run:  ${{github.workspace}}/clang-tidy.sh

      - name: Artifacts
        run:  ${{github.workspace}}/clang-tidy.sh
